[tool.poetry]
name = "slippers"
version = "0.2.0"
description = "Build reusable components in Django without writing a single line of Python."
authors = ["Mitchel Cabuloy <mixxorz@gmail.com>"]
keywords = ["django", "components"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/mixxorz/slippers"
repository = "https://github.com/mixxorz/slippers"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Framework :: Django",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Framework :: Django :: 3.1",
    "Framework :: Django :: 3.2",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6.2"
Django = ">=2.2, <4.0"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
isort = "^5.9.2"
flake8 = "^3.9.2"
ipdb = "^0.13.9"
tox = "^3.23.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
